version: '3.8'

services:
  server:
    build: ./server
    container_name: squat-server
    privileged: true
    ports:
      - "8000:8000"
    restart: always

  client:
    build: ./client
    container_name: squat-client
    ports:
      - "3000:80"
    depends_on:
      - server